### ISSUE TITLE
sheltrex.py 

### ISSUE THREAD

**Issue by OldBo** [paranoidninja/SheltreX#1]
Hello bro! It;s very nice soft. U can upload sheltrex.py to github? 

https://vimeo.com/261693007

I can see it's on video on vimeo. Thank You!

**Comment by paranoidninja** [comment]
That is something that I have shown how to build it previously. You can find the sample here: https://niiconsulting.com/checkmate/2018/03/malware-development-welcome-dark-side-part-3/
