### ISSUE TITLE
+1 on SheltreX Release

### ISSUE THREAD

**Issue by H011YxW00D** [paranoidninja/SheltreX#2]
Hello. Will you be releasing the full code for this including sheltrex.py? I also wanted to know if you would be writing a part 5 malware development article showing how to setup elasticsearch and kibana. These were fantastic write ups! Thank you!

**Comment by paranoidninja** [comment]
I stopped the Elastic part of the malware development since using a mongodb is a much better alternative in my opinion. However, I will be writing a full fledged post on this along with an update
